-- AlterTable
ALTER TABLE "File" ADD COLUMN "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "File" ADD COLUMN "updated_at" DATETIME;

-- AlterTable
ALTER TABLE "Job" ADD COLUMN "created_at" DATETIME DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Job" ADD COLUMN "updated_at" DATETIME;
